env: default

user:
  application:
      home: ~/.TAVI/

library:
  storage:
    raw:
      classification:
        quick: False
  filestore:
    raw:
      size-limit: 1  # MB
ORNL:
  spice:
    file:
      ext: .dat
    metadata:
      field-name:
        def:
          - def_x
          - def_y
  instrument:
    names:
      - HB1A
      - HB1
      - HB3
      - CG4C
